### ISSUE TITLE
Presenting a new iot system

### ISSUE THREAD

**Issue by roccomuso** [ninjablocks/433Utils#15]
Hi guys,

I just wanna show you my new repo that use rc-switch and 433utils. There's something in common with ninjablock and other iot famous project but also really different implementations and features..

https://github.com/roccomuso/iot-433mhz

Any feedback would be appreciated. Thanks!

**Comment by rotv** [comment]
Thanks for sharing and good luck with your project.
For this reported "issue" I recommend that someone closes it since it isn't really an issue with 433Utils.

**Comment by roccomuso** [comment]
@rotv thanks. I'm gonna close by myself :+1:
