### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by ojarva** [ninjablocks/433Utils#22]
This code doesn't seem to include license, which technically means using/forking it is not allowed. If there's no specific concerns about the license, BSD or MIT might be a good choice.

Adding a license is a simple thing for copyright holder - just declare what license will be used in README.md and add `LICENSE` file with appropriate license. See for example https://opensource.org/licenses/BSD-3-Clause

**Comment by jonseymour** [comment]
Now added. That was an oversight - the MIT license applies as it does to all other ninjablocks and ninjasphere repos unless otherwise specified.
