### ISSUE TITLE
Error with "Make" command

### ISSUE THREAD

**Issue by caldecy** [ninjablocks/433Utils#48]
After following all the steps to install WiringPi and 433Utils, I am stuck at the last step of compiling with the command "make".

The error message is as such:
`make: *** No rule to make target '../rc-switch/RCSwitch.o', needed by 'send'.  Stop.
`
Hopefully someone can advise me on this issue! Thanks!

**Comment by rotv** [comment]
Did you do a recursive clone?

**Comment by caldecy** [comment]
Thanks for the quick response! No I didn't and that's why I encountered the problem. 

Thanks for the reminder!
