### ISSUE TITLE
RF_Sniffer compile error

### ISSUE THREAD

**Issue by joeybab3** [ninjablocks/433Utils#5]
When i try to upload or compile it says:
C:\Users\Joey(2)\Documents\Arduino\libraries\RPi_utils\codesend.cpp: In function 'int main(int, char**)':
C:\Users\Joey(2)\Documents\Arduino\libraries\RPi_utils\codesend.cpp:29: error: 'wiringPiSetup' was not declared in this scope

**Comment by rotv** [comment]
Is this issue obsolete?

**Comment by CoffeeAndCream** [comment]
Yeah it sounds like he didn't setup WiringPiSetup

**Comment by rotv** [comment]
Sounds like this issue can be closed.

**Comment by joeybab3** [comment]
Probably ^
